// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_YRq_q-h6BgOD7IVc-dDJkLlQQ432Sw',
    appId: '1:78515627848:web:71db3111c8be046695357d',
    messagingSenderId: '78515627848',
    projectId: 'minesweeper-4ab76',
    authDomain: 'minesweeper-4ab76.firebaseapp.com',
    storageBucket: 'minesweeper-4ab76.appspot.com',
    measurementId: 'G-K1KLW12XB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9asRL03A-Sn2hrV5h78i9asaHe_meEjE',
    appId: '1:78515627848:android:b38721b8a0b4f36d95357d',
    messagingSenderId: '78515627848',
    projectId: 'minesweeper-4ab76',
    storageBucket: 'minesweeper-4ab76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-AITYuG_PH6lZ05i0lS5eSFPY7PDQCI',
    appId: '1:78515627848:ios:472f5eb88dd3a19595357d',
    messagingSenderId: '78515627848',
    projectId: 'minesweeper-4ab76',
    storageBucket: 'minesweeper-4ab76.appspot.com',
    iosClientId: '78515627848-2k16eutr2jv28camfb7oa3d6h6cfoc4g.apps.googleusercontent.com',
    iosBundleId: 'com.gabe.minesweeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-AITYuG_PH6lZ05i0lS5eSFPY7PDQCI',
    appId: '1:78515627848:ios:facd1f8020f2b53595357d',
    messagingSenderId: '78515627848',
    projectId: 'minesweeper-4ab76',
    storageBucket: 'minesweeper-4ab76.appspot.com',
    iosClientId: '78515627848-7nn797440gt8clmio39mc5cpq1mo0ul5.apps.googleusercontent.com',
    iosBundleId: 'com.gabe.minesweeper.RunnerTests',
  );
}
